const ProviderPool = require('../providers/ProviderPool');
const Logger = require('../helpers/logger');

class ImageGenerationService {
  static async generateImage(model, prompt, size, n = 1, options = {}) {
    Logger.info('ImageGenerationService: Starting image generation', { 
      model, 
      prompt,
      size,
      n,
      options
    });
    
    try {
      const results = [];
      for (let i = 0; i < n; i++) {
        const result = await ProviderPool.callModel(model, true, prompt, size, options);
        if (result) {
          results.push(result);
        } else {
          Logger.warn('ImageGenerationService: No result from provider', { model, prompt, size, options });
        }
      }
      
      if (results.length === 0) {
        throw new Error('No images generated by the provider');
      }
      
      Logger.info('ImageGenerationService: Images generated successfully', { count: results.length });
      return results.flat();
    } catch (error) {
      Logger.error(`ImageGenerationService: Error generating image: ${error.message}`, { stack: error.stack });
      throw error;
    }
  }
}

module.exports = ImageGenerationService;