const ProviderPool = require('../providers/ProviderPool');
const Logger = require('../helpers/logger');

class ImageGenerationService {
  static async generateImage(model, prompt, size, n = 1, options = {}) {
    Logger.info('ImageGenerationService: Starting image generation', { 
      model, 
      prompt,
      size,
      n,
      options
    });
    
    try {
      const results = await ProviderPool.callModel(model, true, prompt, size, n, options);
      
      if (!results || results.length === 0) {
        throw new Error('No images generated by the provider');
      }
      
      Logger.info('ImageGenerationService: Images generated successfully', { count: results.length });
      return results;
    } catch (error) {
      Logger.error(`ImageGenerationService: Error generating image: ${error.message}`, { stack: error.stack });
      throw error;
    }
  }
}

module.exports = ImageGenerationService;